"""v1.2.0-real Task 1.2: golden-trace parity oracle for _run_milestone.

Wires the recorder infrastructure from tests/golden_trace_helpers.py into
a full Orchestrator._run_milestone exercise and captures the trace to
tests/golden/v120_baseline.json.

After the v1.2.0-real refactor lands (Tasks 2-9), this same exercise
must produce a byte-identical trace. Any change to: phase-event order,
per-call _accumulate_cost granularity, save_state transition order,
subprocess dispatch, or token shape per call — surfaces as a diff.

The fixture is generated by running the test once with both:
    GOLDEN_TRACE_UPDATE=1
    GOLDEN_TRACE_RATIONALE="initial v1.2.0-real baseline capture"

After that, every CI run re-asserts the trace deep-equals the fixture.

Scope: happy-path only in this commit. Fix-loop fixture lands in a
follow-up commit (Task 1.3), then SwPhase DB roundtrip (Task 1.4), then
Task 2 starts (PhaseBase + PhaseContext + PhaseResult).
"""

from __future__ import annotations

import json
from pathlib import Path

from superpower_workflow.logger import WorkflowLogger
from superpower_workflow.orchestrator import Orchestrator
from superpower_workflow.state import WorkflowState, save_state
from superpower_workflow.telemetry import TelemetryEmitter
from tests.golden_trace_helpers import (
    TraceRecorder,
    assert_trace_matches_fixture,
    install_recorders,
)

FIXTURE_PATH = Path(__file__).parent / "golden" / "v120_baseline.json"


def _build_minimal_project(tmp_path: Path) -> Path:
    """Create a tmp project tree the orchestrator can construct against.

    - tmp_path is the project root (cwd for git operations)
    - tmp_path/.claude/ holds workflow.json + state
    - All optional features OFF so the happy path runs A→B→C→D
      (E skipped via integrations.ci.enabled=False default)
    """
    claude_dir = tmp_path / ".claude"
    claude_dir.mkdir()

    cfg = {
        "schema_version": 1,
        "spec": "spec.md",
        "model": "opus",
        "fallback_model": "haiku",
        "budgets": {"plan": 25, "implement": 25, "review": 10, "push": 3},
        "effort": {"plan": "max", "implement": "high", "review": "max", "push": "low"},
        "verify_commands": {},
        # ONE milestone, no spec_sections to keep prompts simple.
        "milestones": [{"name": "M1"}],
        # Empty plugins → _call_pre_phase / _call_post_phase are no-ops.
        "plugins": {},
        # Empty validation → curator + spec_compliance + feature_verification
        # + strict_mode all skip.
        "validation": {},
        # Empty quality_gates → _verify_quality_gates returns (True, []) immediately.
        "quality_gates": {},
        # No SBOM / signing in Phase D.
        "security": {},
        # No CI → Phase E skipped.
        "integrations": {},
        "convergence": {},
        "telemetry": {"enabled": False},
        "max_total_budget_usd": 100.0,
        # Avoid sleep in retries.
        "delay_between_phases_seconds": 0,
    }
    (claude_dir / "workflow.json").write_text(json.dumps(cfg))

    state = WorkflowState()
    state.run_id = "01TESTRUN1234567890ABCDEFG"
    save_state(claude_dir, state)

    # spec.md is read by the orchestrator's _resolve_spec when constructing
    # prompts. A minimal placeholder is enough since prompts are not
    # validated by the test (we stub run_claude).
    (tmp_path / "spec.md").write_text("# Test spec\n\nMinimal placeholder.\n")

    return tmp_path


def _build_orchestrator(project_root: Path):
    """Construct the Orchestrator and return it ready for install_recorders.

    Orchestrator() leaves _telemetry as None — that's set by Orchestrator.run().
    Since the test invokes _run_milestone directly, install a disabled
    emitter so install_recorders has something to wrap.
    """
    orch = Orchestrator(project_root=project_root)
    orch._telemetry = TelemetryEmitter.disabled()
    return orch


def test_v120_baseline_happy_path(tmp_path, monkeypatch):
    """Capture the canonical happy-path _run_milestone trace.

    Behavior preserved by this fixture:
    - Phase A: pre_phase plugin hook (no-op), state=plan save, save_phase_state,
      PhaseStarted emit, run_claude (call 0), _accumulate_cost,
      _run_gap_curator (returns 0 — disabled), _emit_gap_report (no-op,
      file absent), _emit_gap_validation (no-op), archive_reports (mkdir),
      clear_phase_state, _check_phase_result, PhaseCompleted, post_phase
      hook, git rev-parse for plan_commit_sha, save_state, git tag.
    - Phase B: state=implement, PhaseStarted, run_claude (call 1),
      _accumulate_cost, _verify_quality_gates (returns True immediately —
      no gates configured), PhaseCompleted, post_phase.
    - Phase C: state=review, save_phase_state, PhaseStarted, run_claude (call 2),
      _accumulate_cost, _run_spec_compliance (skipped), _run_feature_verification
      (skipped), _run_gap_curator (0), archive_reports, clear_phase_state,
      _verify_quality_gates, PhaseCompleted, post_phase.
    - Phase D: state=push, pre_commit hook, PhaseStarted, run_claude (call 3),
      _accumulate_cost, PhaseCompleted, post_phase. No SBOM, no signing.
    - Phase E: SKIPPED (integrations.ci.enabled=False).

    Any refactor that reorders these calls, drops one, or adds one will
    diverge from the fixture and surface immediately.
    """
    project_root = _build_minimal_project(tmp_path)
    orch = _build_orchestrator(project_root)

    recorder = TraceRecorder()
    install_recorders(monkeypatch, orch, recorder)

    logger = WorkflowLogger(orch.claude_dir, run_id="testrun")
    try:
        ms = {"name": "M1"}
        cost = orch._run_milestone(ms, logger)
    finally:
        logger.close()

    # Sanity check: cost was accumulated.
    assert cost > 0, f"Expected non-zero cost; got {cost}"
    # Sanity check: at least 4 run_claude calls (one per A/B/C/D).
    assert len(recorder.run_claude_calls) >= 4, (
        f"Expected >=4 run_claude calls (A/B/C/D); got {len(recorder.run_claude_calls)}"
    )

    assert_trace_matches_fixture(recorder, FIXTURE_PATH)


def test_fixture_exists_and_is_non_trivial():
    """Guard: if the fixture file is deleted by accident, this test
    fails with a clear message rather than waiting for the real
    oracle to do a confusing assertion-update step.
    """
    assert FIXTURE_PATH.exists(), (
        f"Golden trace fixture missing: {FIXTURE_PATH}. "
        f"Regenerate with GOLDEN_TRACE_UPDATE=1 and "
        f"GOLDEN_TRACE_RATIONALE=<reason>."
    )
    data = json.loads(FIXTURE_PATH.read_text())
    records = data.get("records", [])
    # A happy-path single-milestone run produces dozens of records.
    # Anything under 20 means we captured a truncated trace.
    assert len(records) >= 20, (
        f"Fixture has only {len(records)} records — expected >=20 for a "
        f"full A→B→C→D run. Probably a partial capture."
    )
