"""v1.2.0-real Task 1.2: golden-trace parity oracle for _run_milestone.

Wires the recorder infrastructure from tests/golden_trace_helpers.py into
a full Orchestrator._run_milestone exercise and captures the trace to
tests/golden/v120_baseline.json.

After the v1.2.0-real refactor lands (Tasks 2-9), this same exercise
must produce a byte-identical trace. Any change to: phase-event order,
per-call _accumulate_cost granularity, save_state transition order,
subprocess dispatch, or token shape per call — surfaces as a diff.

The fixture is generated by running the test once with both:
    GOLDEN_TRACE_UPDATE=1
    GOLDEN_TRACE_RATIONALE="initial v1.2.0-real baseline capture"

After that, every CI run re-asserts the trace deep-equals the fixture.

Scope: happy-path only in this commit. Fix-loop fixture lands in a
follow-up commit (Task 1.3), then SwPhase DB roundtrip (Task 1.4), then
Task 2 starts (PhaseBase + PhaseContext + PhaseResult).
"""

from __future__ import annotations

import json
from pathlib import Path

from superpower_workflow.logger import WorkflowLogger
from superpower_workflow.orchestrator import Orchestrator
from superpower_workflow.state import WorkflowState, save_state
from superpower_workflow.telemetry import TelemetryEmitter
from tests.golden_trace_helpers import (
    TraceRecorder,
    assert_trace_matches_fixture,
    install_recorders,
)

FIXTURE_PATH = Path(__file__).parent / "golden" / "v120_baseline.json"
FIXLOOP_FIXTURE_PATH = Path(__file__).parent / "golden" / "v120_fixloop.json"


def _build_minimal_project(tmp_path: Path) -> Path:
    """Create a tmp project tree the orchestrator can construct against.

    - tmp_path is the project root (cwd for git operations)
    - tmp_path/.claude/ holds workflow.json + state
    - All optional features OFF so the happy path runs A→B→C→D
      (E skipped via integrations.ci.enabled=False default)
    """
    claude_dir = tmp_path / ".claude"
    claude_dir.mkdir()

    cfg = {
        "schema_version": 1,
        "spec": "spec.md",
        "model": "opus",
        "fallback_model": "haiku",
        "budgets": {"plan": 25, "implement": 25, "review": 10, "push": 3},
        "effort": {"plan": "max", "implement": "high", "review": "max", "push": "low"},
        "verify_commands": {},
        # ONE milestone, no spec_sections to keep prompts simple.
        "milestones": [{"name": "M1"}],
        # Empty plugins → _call_pre_phase / _call_post_phase are no-ops.
        "plugins": {},
        # Empty validation → curator + spec_compliance + feature_verification
        # + strict_mode all skip.
        "validation": {},
        # Empty quality_gates → _verify_quality_gates returns (True, []) immediately.
        "quality_gates": {},
        # No SBOM / signing in Phase D.
        "security": {},
        # No CI → Phase E skipped.
        "integrations": {},
        "convergence": {},
        "telemetry": {"enabled": False},
        "max_total_budget_usd": 100.0,
        # Avoid sleep in retries.
        "delay_between_phases_seconds": 0,
    }
    (claude_dir / "workflow.json").write_text(json.dumps(cfg))

    state = WorkflowState()
    state.run_id = "01TESTRUN1234567890ABCDEFG"
    save_state(claude_dir, state)

    # spec.md is read by the orchestrator's _resolve_spec when constructing
    # prompts. A minimal placeholder is enough since prompts are not
    # validated by the test (we stub run_claude).
    (tmp_path / "spec.md").write_text("# Test spec\n\nMinimal placeholder.\n")

    return tmp_path


def _build_fixloop_project(tmp_path: Path) -> Path:
    """Build a project tree with quality_gates enabled so the fix-loop fires.

    Same as _build_minimal_project except quality_gates configures one gate
    (lint → 'ruff check .'). The test combines this with a stateful
    subprocess dispatcher that makes the first gate call fail, triggering
    Phase B's fix-loop (fix-prompt claude call + _accumulate_cost + recheck).
    QG#2 in Phase C then runs the gate again (which now passes on first try).
    """
    claude_dir = tmp_path / ".claude"
    claude_dir.mkdir()

    cfg = {
        "schema_version": 1,
        "spec": "spec.md",
        "model": "opus",
        "fallback_model": "haiku",
        "budgets": {"plan": 25, "implement": 25, "review": 10, "push": 3},
        "effort": {"plan": "max", "implement": "high", "review": "max", "push": "low"},
        "verify_commands": {},
        "milestones": [{"name": "M1"}],
        "plugins": {},
        "validation": {},
        # Only one gate so the fix-loop counts are easy to reason about.
        # Each QG checkpoint runs this command once; first call fails,
        # subsequent pass (the test wires the stateful dispatcher).
        "quality_gates": {"lint": "ruff check ."},
        "security": {},
        "integrations": {},
        "convergence": {},
        "telemetry": {"enabled": False},
        "max_total_budget_usd": 100.0,
        "delay_between_phases_seconds": 0,
    }
    (claude_dir / "workflow.json").write_text(json.dumps(cfg))

    state = WorkflowState()
    state.run_id = "01TESTFIX0987654321ABCDEFG"
    save_state(claude_dir, state)

    (tmp_path / "spec.md").write_text("# Test spec\n\nMinimal placeholder.\n")
    return tmp_path


def _build_orchestrator(project_root: Path):
    """Construct the Orchestrator and return it ready for install_recorders.

    Orchestrator() leaves _telemetry as None — that's set by Orchestrator.run().
    Since the test invokes _run_milestone directly, install a disabled
    emitter so install_recorders has something to wrap.
    """
    orch = Orchestrator(project_root=project_root)
    orch._telemetry = TelemetryEmitter.disabled()
    return orch


def test_v120_baseline_happy_path(tmp_path, monkeypatch):
    """Capture the canonical happy-path _run_milestone trace.

    Behavior preserved by this fixture:
    - Phase A: pre_phase plugin hook (no-op), state=plan save, save_phase_state,
      PhaseStarted emit, run_claude (call 0), _accumulate_cost,
      _run_gap_curator (returns 0 — disabled), _emit_gap_report (no-op,
      file absent), _emit_gap_validation (no-op), archive_reports (mkdir),
      clear_phase_state, _check_phase_result, PhaseCompleted, post_phase
      hook, git rev-parse for plan_commit_sha, save_state, git tag.
    - Phase B: state=implement, PhaseStarted, run_claude (call 1),
      _accumulate_cost, _verify_quality_gates (returns True immediately —
      no gates configured), PhaseCompleted, post_phase.
    - Phase C: state=review, save_phase_state, PhaseStarted, run_claude (call 2),
      _accumulate_cost, _run_spec_compliance (skipped), _run_feature_verification
      (skipped), _run_gap_curator (0), archive_reports, clear_phase_state,
      _verify_quality_gates, PhaseCompleted, post_phase.
    - Phase D: state=push, pre_commit hook, PhaseStarted, run_claude (call 3),
      _accumulate_cost, PhaseCompleted, post_phase. No SBOM, no signing.
    - Phase E: SKIPPED (integrations.ci.enabled=False).

    Any refactor that reorders these calls, drops one, or adds one will
    diverge from the fixture and surface immediately.
    """
    project_root = _build_minimal_project(tmp_path)
    orch = _build_orchestrator(project_root)

    recorder = TraceRecorder()
    install_recorders(monkeypatch, orch, recorder)

    logger = WorkflowLogger(orch.claude_dir, run_id="testrun")
    try:
        ms = {"name": "M1"}
        cost = orch._run_milestone(ms, logger)
    finally:
        logger.close()

    # Sanity check: cost was accumulated.
    assert cost > 0, f"Expected non-zero cost; got {cost}"
    # Sanity check: at least 4 run_claude calls (one per A/B/C/D).
    assert len(recorder.run_claude_calls) >= 4, (
        f"Expected >=4 run_claude calls (A/B/C/D); got {len(recorder.run_claude_calls)}"
    )

    assert_trace_matches_fixture(recorder, FIXTURE_PATH)


def test_fixture_exists_and_is_non_trivial():
    """Guard: if the fixture file is deleted by accident, this test
    fails with a clear message rather than waiting for the real
    oracle to do a confusing assertion-update step.
    """
    assert FIXTURE_PATH.exists(), (
        f"Golden trace fixture missing: {FIXTURE_PATH}. "
        f"Regenerate with GOLDEN_TRACE_UPDATE=1 and "
        f"GOLDEN_TRACE_RATIONALE=<reason>."
    )
    data = json.loads(FIXTURE_PATH.read_text())
    records = data.get("records", [])
    # A happy-path single-milestone run produces dozens of records.
    # Anything under 20 means we captured a truncated trace.
    assert len(records) >= 20, (
        f"Fixture has only {len(records)} records — expected >=20 for a "
        f"full A→B→C→D run. Probably a partial capture."
    )


def test_v120_fixloop_quality_gate(tmp_path, monkeypatch):
    """Capture the QG#1 fix-loop trace.

    Setup: quality_gates configures one gate (`lint → ruff check .`). The
    stateful dispatcher makes the first gate call return rc=1, and all
    subsequent calls return rc=0. The flow then exercises:

    - Phase A: same as happy path (no gates run during plan).
    - Phase B: primary claude → QG#1 lint call #1 (rc=1, fails) → fix-loop
      prompt claude call → _accumulate_cost on fix-loop cost → QG#1 lint
      call #2 (rc=0, passes) → policy check (no policies configured) →
      coverage → context refresh → spec_compliance + feature_verification
      (both skipped, validation empty) → PhaseCompleted.
    - Phase C: primary claude → QG#2 lint call #3 (rc=0, passes first try
      — no fix-loop) → PhaseCompleted.
    - Phase D: same as happy path.

    The fix-loop adds: 1 extra run_claude, 1 extra _accumulate_cost (on
    fix-loop cost — this is the v1.3.12 in-flight gate granularity that
    must survive the refactor), 1 extra QG subprocess call. Trace
    expected to be ~5-8 records longer than the happy-path baseline.

    A refactor that drops the per-call _accumulate_cost inside the
    fix-loop (Finding 1 regression) collapses the accumulate_cost record
    count by 1 — surfaces as a diff at the corresponding call_index.
    """
    project_root = _build_fixloop_project(tmp_path)
    orch = _build_orchestrator(project_root)

    recorder = TraceRecorder()
    # First gate call fails, all subsequent pass — triggers Phase B's
    # QG#1 fix-loop exactly once.
    install_recorders(
        monkeypatch,
        orch,
        recorder,
        gate_returncode=lambda idx, cmd: 1 if idx == 0 else 0,
    )

    logger = WorkflowLogger(orch.claude_dir, run_id="testfix")
    try:
        cost = orch._run_milestone({"name": "M1"}, logger)
    finally:
        logger.close()

    # Sanity: fix-loop ran (1 extra claude call vs happy path).
    assert len(recorder.run_claude_calls) >= 5, (
        f"Expected >=5 run_claude calls (A/B/B-fix/C/D); got {len(recorder.run_claude_calls)}"
    )
    # Sanity: at least one gate call failed (rc=1 path was exercised).
    gate_calls = [r for r in recorder.subprocess_calls if r.payload["head"] != "git"]
    assert len(gate_calls) >= 2, (
        f"Expected >=2 gate calls (QG#1 fail + recheck); got {len(gate_calls)}"
    )
    assert cost > 0

    assert_trace_matches_fixture(recorder, FIXLOOP_FIXTURE_PATH)


def test_fixloop_fixture_exists_and_diverges_from_baseline():
    """The fix-loop fixture must exist and must be strictly larger than
    the happy-path baseline (because the fix-loop adds claude calls,
    accumulate_cost calls, and gate subprocess calls). If both fixtures
    had the same record count, the dispatcher's fail-then-pass logic
    isn't binding.
    """
    assert FIXLOOP_FIXTURE_PATH.exists(), f"Fix-loop fixture missing: {FIXLOOP_FIXTURE_PATH}."
    baseline = json.loads(FIXTURE_PATH.read_text())
    fixloop = json.loads(FIXLOOP_FIXTURE_PATH.read_text())
    n_baseline = len(baseline.get("records", []))
    n_fixloop = len(fixloop.get("records", []))
    assert n_fixloop > n_baseline, (
        f"Fix-loop fixture ({n_fixloop} records) should be strictly larger "
        f"than baseline ({n_baseline} records). Same size suggests the "
        f"fail-then-pass dispatcher didn't bind."
    )
