from __future__ import annotations

import json
import re
import subprocess
from typing import Any


def parse_issue_ref(ref: str, default_repo: str = "") -> tuple[str, int]:
    ref = ref.strip().lstrip("#")
    if "#" in ref:
        parts = ref.split("#", 1)
        repo = parts[0] or default_repo
        number = int(parts[1])
    else:
        repo = default_repo
        number = int(ref)
    return repo, number


def fetch_issue(issue_ref: str, default_repo: str = "", cwd: str = ".") -> dict[str, Any]:
    repo, number = parse_issue_ref(issue_ref, default_repo)
    cmd = [
        "gh",
        "issue",
        "view",
        str(number),
        "--json",
        "title,body,labels,assignees",
    ]
    if repo:
        cmd.extend(["--repo", repo])
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, cwd=cwd, timeout=30)
    except FileNotFoundError:
        raise RuntimeError("gh CLI not found. Install from https://cli.github.com/") from None
    if result.returncode != 0:
        raise RuntimeError(f"Failed to fetch issue {issue_ref}: {result.stderr.strip()}")
    return json.loads(result.stdout)


def _slugify(title: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    return slug[:50]


def issue_to_milestone(
    issue_data: dict[str, Any],
    label_map: dict[str, str] | None = None,
) -> dict[str, Any]:
    title = issue_data.get("title", "untitled")
    ms: dict[str, Any] = {
        "name": _slugify(title),
        "description": title,
        "spec_sections": issue_data.get("body", ""),
        "depends_on": [],
    }
    if label_map:
        labels = [lb.get("name", "") for lb in issue_data.get("labels", [])]
        for label in labels:
            if label in label_map:
                ms["type"] = label_map[label]
                break
        if "type" not in ms:
            ms["type"] = ""
    return ms


def render_pr_body(
    milestone: str,
    description: str = "",
    changes: str = "",
    cost_usd: float = 0.0,
    duration_seconds: float = 0.0,
    test_count: int = 0,
    coverage_pct: float = 0.0,
    total_tokens: int = 0,
) -> str:
    from superpower_workflow import __version__

    sections = [f"## {milestone}", ""]
    if description:
        sections.append(description)
        sections.append("")
    if changes:
        sections.extend(["### Changes", changes, ""])
    sections.append("### Test Results")
    sections.append(f"- Tests added: {test_count}")
    if coverage_pct > 0:
        sections.append(f"- Coverage: {coverage_pct:.0f}%")
    sections.append("")
    sections.append("### Cost")
    if total_tokens > 0:
        sections.append(f"- Tokens: {total_tokens}")
    sections.append(f"- Cost: ${cost_usd:.2f}")
    if duration_seconds > 0:
        sections.append(f"- Duration: {duration_seconds:.0f}s")
    sections.append("")
    sections.append(f"Generated by superpower-workflow v{__version__}")
    return "\n".join(sections)


def create_pr(
    title: str,
    body: str,
    branch: str,
    base: str = "main",
    cwd: str = ".",
    repo: str = "",
) -> str:
    cmd = [
        "gh",
        "pr",
        "create",
        "--title",
        title,
        "--body",
        body,
        "--head",
        branch,
        "--base",
        base,
    ]
    if repo:
        cmd.extend(["--repo", repo])
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=cwd, timeout=30)
    if result.returncode != 0:
        return ""
    return result.stdout.strip()
